name: Workflow As Kubernetes Initialization

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: kerthcet/github-workflow-as-kube/.github/workflows/workflow-as-kubernetes-init.yaml@v0.1.11
    secrets:
      AGENT_TOKEN: ${{ secrets.AGENT_TOKEN }}
